environment             = "dev"
vpc_cidr                = "10.0.0.0/16"
public_subnets_cidr     = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnets_cidr    = ["10.0.10.0/24", "10.0.11.0/24"]
availability_zones      = ["us-east-1a", "us-east-1b"]
aws_region              = "us-east-1"
db_instance_class       = "db.t3.micro"
db_password             = "temporarydevpassword"
app_name                = "myphpapp"
fargate_cpu             = 256
fargate_memory          = 512
app_count               = 1
github_repo_owner       = "Jagadeesh-AI2911"
github_repo_name        = "projects"
github_branch           = "main"